In [3]:
!pip install tensorflow numpy

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

with open("C:\\Users\\muham\\Desktop\\news.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()


In [5]:
mytext

'Who is Imran Khan?\nImran Khan is a former international cricketer and is the 22nd Prime Minister of Pakistan. Other than being the captain of the Pakistan national cricket team, he was chancellor of the University of Bradford in the United Kingdom from 2005 and 2014. In 1996, Khan founded the Pakistan Tehreek-e-Insaf and serves as its chairman. In memory of his mother, he launched a fundraising campaign to set up a cancer hospital in Lahore and raised $25 million.\n \nBorn in Lahore, his paternal family are of Pashtun ethnicity and belong to the Niazi tribe. Khan grew up with his four sisters in upper-middle-class circumstances. He was educated at the Royal Grammar School Worcester in England, where he excelled at cricket. He enrolled in Keble College, Oxford in 1972 where he studied Philosophy, Politics, and Economics, graduating in 1975.\n\nCricketing years\n \nKhan made his Test cricket debut against England in 1971 at Edgbaston. In 1976, he returned to Pakistan and secured a perm

In [6]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [7]:
mytokenizer.word_index

{'the': 1,
 'of': 2,
 'in': 3,
 'and': 4,
 'to': 5,
 'a': 6,
 'pakistan': 7,
 'on': 8,
 'khan': 9,
 'he': 10,
 'pti': 11,
 'his': 12,
 'was': 13,
 'election': 14,
 'as': 15,
 'with': 16,
 'an': 17,
 'is': 18,
 'imran': 19,
 'lahore': 20,
 'at': 21,
 'against': 22,
 'for': 23,
 'had': 24,
 'court': 25,
 'protests': 26,
 'its': 27,
 'during': 28,
 'order': 29,
 'party': 30,
 '9': 31,
 'ecp': 32,
 'cricket': 33,
 'from': 34,
 'tehreek': 35,
 'e': 36,
 'insaf': 37,
 'test': 38,
 'general': 39,
 'two': 40,
 'commission': 41,
 'that': 42,
 'may': 43,
 'were': 44,
 'phc': 45,
 'intra': 46,
 'national': 47,
 'team': 48,
 'chairman': 49,
 'has': 50,
 'over': 51,
 'including': 52,
 'pakistani': 53,
 'mianwali': 54,
 '2011': 55,
 'out': 56,
 'state': 57,
 'hold': 58,
 'related': 59,
 'workers': 60,
 'x': 61,
 'now': 62,
 'high': 63,
 'decision': 64,
 'symbol': 65,
 'december': 66,
 'it': 67,
 'passed': 68,
 'former': 69,
 'international': 70,
 'prime': 71,
 'minister': 72,
 'other': 73,
 'than': 

In [9]:
my_input_sequences = []
for line in mytext.split('\n'):
    # print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        # print(input_sequences)


[137, 18, 19, 9]
[137, 18]
[137, 18, 19]
[137, 18, 19, 9]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72, 2, 7, 73, 74, 140, 1, 141, 2, 1, 7, 47, 33, 48, 10, 13, 142, 2, 1, 143, 2, 144, 3, 1, 75, 145, 34, 146, 4, 147, 3, 76, 9, 77, 1, 7, 35, 36, 37, 4, 148, 15, 27, 49, 3, 149, 2, 12, 150, 10, 151, 6, 152, 153, 5, 154, 78, 6, 155, 156, 3, 20, 4, 157, 79, 158]
[19, 9]
[19, 9, 18]
[19, 9, 18, 6]
[19, 9, 18, 6, 69]
[19, 9, 18, 6, 69, 70]
[19, 9, 18, 6, 69, 70, 138]
[19, 9, 18, 6, 69, 70, 138, 4]
[19, 9, 18, 6, 69, 70, 138, 4, 18]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72, 2]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72, 2, 7]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72, 2, 7, 73]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72, 2, 7, 73, 74]
[19, 9, 18, 6, 69, 70, 138, 4, 18, 1, 139, 71, 72

In [10]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen = max_sequence_len, padding='pre'))

In [11]:
input_sequences[20]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  19,   9,  18,   6,  69,  70,
       138,   4,  18,   1, 139,  71,  72,   2,   7,  73,  74, 140,   1])

In [12]:
x = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [34]:
x[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 137])

In [14]:
y[4]

18

In [15]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [16]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [17]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length = max_sequence_len-1)) 
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 77, 100)           49900     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 499)               75349     
                                                                 
Total params: 275849 (1.05 MB)
Trainable params: 275849 (1.05 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [18]:
model.compile(loss="categorical_crossentropy", optimizer = 'adam', metrics=['accuracy']) 
model.fit(x, y, epochs = 100, verbose = 1)


Epoch 1/100


34/34 [==============================] - 6s 83ms/step - loss: 5.9992 - accuracy: 0.0631
Epoch 2/100
34/34 [==============================] - 3s 80ms/step - loss: 5.6269 - accuracy: 0.0716
Epoch 3/100
34/34 [==============================] - 3s 85ms/step - loss: 5.5483 - accuracy: 0.0716
Epoch 4/100
34/34 [==============================] - 5s 134ms/step - loss: 5.4980 - accuracy: 0.0716
Epoch 5/100
34/34 [==============================] - 3s 82ms/step - loss: 5.4477 - accuracy: 0.0716
Epoch 6/100
34/34 [==============================] - 3s 95ms/step - loss: 5.3679 - accuracy: 0.0716
Epoch 7/100
34/34 [==============================] - 4s 128ms/step - loss: 5.2739 - accuracy: 0.0725
Epoch 8/100
34/34 [==============================] - 4s 122ms/step - loss: 5.1500 - accuracy: 0.0857
Epoch 9/100
34/34 [==============================] - 3s 90ms/step - loss: 5.0197 - accuracy: 0.1008
Epoch 10/100
34/34 [==============================] - 4s 110ms/step - loss: 4.8615 - accuracy:

34/34 [==============================] - 3s 84ms/step - loss: 0.0776 - accuracy: 0.9906
Epoch 76/100
34/34 [==============================] - 4s 115ms/step - loss: 0.0758 - accuracy: 0.9896
Epoch 77/100
34/34 [==============================] - 3s 87ms/step - loss: 0.0733 - accuracy: 0.9906
Epoch 78/100
34/34 [==============================] - 3s 95ms/step - loss: 0.0720 - accuracy: 0.9906
Epoch 79/100
34/34 [==============================] - 3s 94ms/step - loss: 0.0701 - accuracy: 0.9906
Epoch 80/100
34/34 [==============================] - 4s 106ms/step - loss: 0.0672 - accuracy: 0.9915
Epoch 81/100
34/34 [==============================] - 5s 143ms/step - loss: 0.0652 - accuracy: 0.9915
Epoch 82/100
34/34 [==============================] - 5s 155ms/step - loss: 0.0634 - accuracy: 0.9906
Epoch 83/100
34/34 [==============================] - 5s 141ms/step - loss: 0.0619 - accuracy: 0.9906
Epoch 84/100
34/34 [==============================] - 4s 124ms/step - loss: 0.0605 - accuracy: 0.99

In [21]:
input_text = "khan"
predict_next_words = 10

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len - 1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    
    input_text += " " + output_word
    print(input_text)


[9]
1/1 [==============================] - 0s 21ms/step
khan made
[9, 83]
1/1 [==============================] - 0s 27ms/step
khan made his
[9, 83, 12]
1/1 [==============================] - 0s 17ms/step
khan made his test
[9, 83, 12, 38]
1/1 [==============================] - 0s 26ms/step
khan made his test cricket
[9, 83, 12, 38, 33]
1/1 [==============================] - 0s 31ms/step
khan made his test cricket debut
[9, 83, 12, 38, 33, 193]
1/1 [==============================] - 0s 31ms/step
khan made his test cricket debut against
[9, 83, 12, 38, 33, 193, 22]
1/1 [==============================] - 0s 19ms/step
khan made his test cricket debut against england
[9, 83, 12, 38, 33, 193, 22, 80]
1/1 [==============================] - 0s 17ms/step
khan made his test cricket debut against england in
[9, 83, 12, 38, 33, 193, 22, 80, 3]
1/1 [==============================] - 0s 37ms/step
khan made his test cricket debut against england in 1971
[9, 83, 12, 38, 33, 193, 22, 80, 3, 194]
1/1 [=